export const LOAD_TODOS = "LOAD_TODOS";
export const LOAD_LISTINGS = "LOAD_LISTINGS";
export const CREATE_LISTING = "CREATE_LISTING";
export const DELETE_LISTING = "DELETE_LISTING";
export const EDIT_LISTING = "EDIT_LISTING";
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";